config/routes.rb
Rails.application.routes.draw do
  resources :travel_agencies do
    resources :getaways, only: [:new, :index]
  end
  resources :excursions
  resources :trips
  resources :accommodations
  resources :getaways
  root 'static#home'
  get '/dashboard' => 'static#dashboard', as: :dashboard
  get '/signup' => 'users#new'
  get '/login'  => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get 'flights' => 'getaways#flights', as: :flight
  get 'roadtrips' => 'getaways#roadtrips', as: :roadtrip
  get '/auth/facebook/callback' => 'sessions#fb_create'
  get '/users/toptwo' => 'users#toptwo', as: :top_users
  resources :users



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/accommodation.rb
class Accommodation < ApplicationRecord
    belongs_to :getaway
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/excursion.rb
class Excursion < ApplicationRecord
    belongs_to :getaway
end

app/models/getaway.rb
class Getaway < ApplicationRecord
    belongs_to :user
    belongs_to :travel_agency, optional: true
    has_many :accommodations
    has_many :excursions
    has_many :trips
    scope :flights, -> { joins(:trips).where('trips.flight = true') }
    scope :road_trips, -> { joins(:trips).where('trips.road_trip = true') }

    accepts_nested_attributes_for :trips, :accommodations

end

app/models/travel_agency.rb
class TravelAgency < ApplicationRecord
    has_many :getaways

    has_many :trips, through: :getaways
    has_many :accommodations, through: :getaways
    has_many :excursions, through: :getaways
    has_many :users, through: :getaways


end

app/models/trip.rb
class Trip < ApplicationRecord
    belongs_to :getaway
    validates :duration, numericality: true

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :username, presence: true
    validates :username, uniqueness: true
    has_many :getaways
    has_many :trips, through: :getaways
    has_many :accommodations, through: :getaways
    has_many :excursions, through: :getaways
    has_many :travel_agencies, through: :getaways
    scope :top_two, -> { joins(:getaways).group('users.id').order('COUNT(users.id) desc').limit(2) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ApplicationHelper


end

app/controllers/excursions_controller.rb
class ExcursionsController < ApplicationController
end

app/controllers/getaways_controller.rb
class GetawaysController < ApplicationController
before_action :set_getaway, only: [:show, :edit, :update, :destroy]
    def new
          @getaway = Getaway.new
          @getaway.trips.build
          @getaway.accommodations.build
          
      end
    
    
      def create
        @getaway = Getaway.new(getaway_params)
        @getaway.user = current_user
        if @getaway.save
          redirect_to getaway_path(@getaway)
        else
          render :new
        end
      end

      def index
        @getaways = Getaway.all
      end

      def flights
        @getaways = Getaway.all.flights
        render :index
      end

      def roadtrips
        @getaways = Getaway.all.road_trips
        render :index
      end

      def show
        @accommodation = @getaway.accommodations.first
      end

      def edit
      end

      def update
          if is_owner?(@getaway) && @getaway.update(getaway_params)
            redirect_to getaway_path(@getaway)
          else
            render :edit
          end
      end

      def destroy
        @getaway.destroy
        redirect_to getaways_path
      end

      private

      def set_getaway
        @getaway = Getaway.find_by(id: params[:id])
        if !@getaway
          redirect_to getaways_path
        end
      end

      def getaway_params
        params.require(:getaway).permit(:title, :days, :accommodations, :travel_agency_id, :travel_agency_attributes => [:name, :id], :trips_attributes => [:flight, :road_trip, :duration, :id], :accommodations_attributes => [:name, :address, :city, :state, :id] )
      end
    

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        @user = User.new
        render :login
    end

    def create
        @user = User.find_by(username: params[:user][:username])
        if @user && @user.authenticate(params[:user][:password])
            session[:user_id] = @user.id 
            redirect_to dashboard_path
        else
            redirect_to '/login'
        end
    end


    def destroy
        session.clear 
        redirect_to '/'
    end

    def fb_create
        @user = User.find_or_create_by(uid: auth['uid']) do |u|
            u.username = auth['info']['name']
            u.password = auth['uid'] 
          end
     
        session[:user_id] = @user.id
     
        redirect_to dashboard_path
      end
     
      private
     
      def auth
        request.env['omniauth.auth']
      end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    def home
    end

    def dashboard
        @getaways = Getaway.last(3)
    end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def new
    @user = User.new
end

def create 
    @user = User.new(user_params)

    if @user.save
        session[:user_id] = @user.id
        redirect_to dashboard_path
    else 
        render :new
    end
end


def toptwo
@users = User.top_two
render :top_two
end
private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/accommodations_helper.rb
module AccommodationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_user
        @current_user ||= User.find_by_id(session[:user_id])
      end
  
      def logged_in?
        !!session[:user_id]
      end

      def is_owner?(getaway)
        getaway.user_id == current_user.id 
      end

end

app/helpers/excursions_helper.rb
module ExcursionsHelper
end

app/helpers/getaways_helper.rb
module GetawaysHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/travel_agencies_helper.rb
module TravelAgenciesHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
end

app/views/getaways/_form.html.erb
<%= form_for(@getaway) do |f| %>
<div class="box">
<%= render partial: 'layouts/errors', locals: {object: @getaway} %>
  <%= f.label :title, class: "label" %>
  <br />
  <%= f.text_field :title, class: "input" %>

<br />
  Number of <%= f.label :days %>
  <br />
  <%= f.number_field :days, min: 2, max: 4 %>
 <br />
  <%= f.fields_for :trips do |trip| %>
    <%= trip.label :road_trip, class: "label" %>
    <%= trip.check_box :road_trip %>

    <%= trip.label :flight, class: "label" %>
    <%= trip.check_box :flight %>
  <br />
    <%= trip.label :duration%> of Trip
    <br />
    <%= trip.text_field :duration, class: "input" %> Hours
  <% end %>

<br />

<h3 class="subtitle">Lodging Information</h3>
<%= f.fields_for :accommodations do |acc| %>
    <%= acc.label :name, class: "label" %>
    <br />
    <%= acc.text_field :name, class: "input" %><br>
<br />
    <%= acc.label :address, class: "label" %>
    <br />
    <%= acc.text_field :address, class: "input" %><br>

    <%= acc.label :city, class: "label" %>
    <br />
    <%= acc.text_field :city, class: "input" %><br>

    <%= acc.label :state, class: "label" %>
    <br />
    <%= acc.text_field :state, class: "input" %><br>
  <% end %>

<h3 class="subtitle"> Using a Travel Agency? </h3>
  <%= f.label :travel_agency_id, "Select Travel Agency", class: "label" %>
  <%= f.collection_select :travel_agency_id, TravelAgency.all, :id, :name, prompt: true %>
<br />
  <%= f.submit "Create Getaway", class: "button is-link is-fullwidth space" %>
  <% end %>
</div>

app/views/getaways/edit.html.erb
<h1>Edit Getaway</h1>

 <%= render 'form' %>

app/views/getaways/index.html.erb
<section class="hero is-dark is-medium">
<div class="hero-body">
   <div class="container has-text-centered">
<h1 class="title is-1">  Be Inspired by Getaways Created By Users Like You! </h1>
</div>
</div>
</section>




<% @getaways.each do |g| %>
<div class="box">
<%= g.title %>
<% if g.accommodations %>
<% g.accommodations.each do |acc| %>
<%= acc.city %>
<% end %>
<% end %>
<%= link_to "See this Getaway", getaway_path(g), :class => "button is-fullwidth is-link"%>
<br>
</div>
<% end %>

<div class="buttons">
<%= link_to "Create a Getaway", new_getaway_path, :class => "button is-fullwidth is-link" %>
<%= link_to "Return to Homepage", dashboard_path, :class => "button is-fullwidth is-link" %>
</div>

app/views/getaways/new.html.erb
<section class="hero is-dark is-medium">
<div class="hero-body">
   <div class="container has-text-centered">
<h1 class="title is-1">  Create a Getaway  </h1>
</div>
</div>
</section>
 <%= render 'form' %>

app/views/getaways/show.html.erb
<section class="hero is-dark is-medium">
<div class="hero-body">
   <div class="container has-text-centered">
<h1 class="title is-1">   <%= @getaway.title %> </h1>
<h3 class="subtitle"> Created by: <%= @getaway.user.username %> </h3>
</div>
</div>
</section>


<div class="box">
<p>Destination: <%= @accommodation.city %>, <%= @accommodation.state %> </p>
<h3> Staying At: </h3>
<% @getaway.accommodations.each do |acc| %>
<%= acc.name %>
<br>
<%= acc.address %>
<% end %>
<br>
<h3> Travel Details: </h3>
<% @getaway.trips.each do |t| %>
<% if t.road_trip == true %>
<%= t.duration %> Hour Road Trip
<% elsif t.flight == true %> 
<%= t.duration %> Hour flight
<% else %>
<%= t.duration %> Hour trip 
<% end %>
<% end %>
</div>

<div class="buttons">
<%= link_to "Back To Dashboard", dashboard_path, :class => "button is-fullwidth is-link"%>
<% if is_owner?(@getaway) %>
<%= link_to "Edit Getaway", edit_getaway_path(@getaway), :class => "button is-fullwidth is-link"%>
<%= link_to "Delete Getaway", getaway_path(@getaway), method: :delete, :class => "button is-fullwidth is-link"%>
<% end %>
</div>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
<%= render partial: 'layouts/errors', locals: {object: @user} %>
<%= f.label :username %>
<%= f.text_field :username %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.submit "Sign Up"%>

<% end %>

app/views/users/top_two.html.erb
<% @users.each do |user| %>
    <%= user.username %>
<% end %>